### ISSUE TITLE
Set up Github Actions

### ISSUE THREAD

**Issue by deanhaleem** [deanhaleem/mario-clone-ts#21]
### Description

Definitely want an action for unit tests. Look into others. Long term, will have one for integration and end to end tests once we get there.

### TODO

- [x] Configure Github action for unit tests
- [x] Configure other useful github action
- [x] Document how to configure actions for future use
- [x] Checkout popular repos and their actions
  - [undici](https://github.com/nodejs/undici/actions/workflows/bench.yml) 

### Dependencies
#20
