### ISSUE TITLE
Implement User Input

### ISSUE THREAD

**Issue by deanhaleem** [deanhaleem/mario-clone-ts#27]
### Description

Allow users to interact with the game

### TODO

- [x] Check out Phaser's docs on user input and see if they have anything useful
  - Result: they do actually, `isDown`, `isUp`, and can hook up events to fire, but for now just stick with old code 
- [x] Implement KeyboardController class
  - Use command pattern if Phaser doesn't have anything useful
- [x] Hook up keyboard input to moving Player game object around

### Implementation Notes
- Can get the keys on the keyboard using `input.keyboard.keys`, but will need to check if they're down myself. Not a big deal, just another loop.
- `KeyboardController` will need to store that `input.keyboard` object from the scene

### Old Code Notes
- Rather than using an `isKeyUp` method, just kept an array of keys that were pressed in the previous frame
- Really the only monogame method I used was to get all the keys currently being pressed on that frame
- Keys were passed in from external object. The Game States. Which makes sense in long term
